server:
  port: 9002
  netty:
    shutdown: graceful
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: pedido-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: user123
    url: r2dbc:postgresql://localhost:5432/lojadb_pedido
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/lojadb_pedido
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    stream:
      bindings:
        paymentProcess-out-0:
          destination: payment-accepted
  rabbitmq:
    bindings:
      paymentProcess-out-0:
        producer:
          transacted: true
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

loja:
  catalog-service-uri: "http://localhost:9001"
  temp-limit: 5