version: "3.8"

services:
  order-products:
    depends_on:
      - loja-postgres
      - loja-rabbitmq
    image: "ghcr.io/erickknsilva/pedido-service"
    container_name: "order-products"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - BPL_JVM_THREAD_COUNT=10
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - LOJA_CATALOG_SERVICE_URI=http://catalog-products:9001
      - SPRING_R2DBC_URL=r2dbc:postgresql://loja-postgres:5432/lojadb_pedido
      - SPRING_FLYWAY_URL=jdbc:postgresql://loja-postgres:5432/lojadb_pedido

  loja-postgres:
    image: "postgres:14.4"
    container_name: "loja-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  loja-rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: "loja-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

